services:
  umbraco:
    build: .
    ports:
      - "80:80"
    environment:
      ConnectionStrings__umbracoDbDSN: "Server=db;Database=UmbracoDb;User=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      - db
    volumes:
      - ./app_data:/app/App_Data
      - ./media:/app/wwwroot/media

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Pass123"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
